[package]
name = "absolute-remap"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = "0.13.2"
uinput = "0.1.3"
anyhow = "1.0.102"
clap = { version = "4.3.19", features = ["derive"] }
# clap_complete = "4.3.2"
log = "0.4.19"
simplelog = "0.12.2"
colored = "3.1.1"